const exploredata = [
    {
      id: 1,
      name: 'ZARA',
      imageSrc: 'https://images.unsplash.com/photo-1583001810204-ac030157288f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1887&q=80',
      imageAlt: '',
      detail: 'Brand new series from zara',
      imageProfile: '',
    },
    {
      id: 2,
      name: 'NIKE',
      imageSrc: 'https://images.unsplash.com/photo-1582113943690-eb2d7b74cdb5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTl8fG5pa2UlMjBjbG90aGluZ3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      imageAlt: '',
      detail:'asdasdaaa',
      imageProfile: '',
    },
    {
      id: 3,
      name: 'ADIDAS',
      imageSrc: 'https://images.unsplash.com/photo-1598403031688-e7cfd2c222c4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTd8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      imageAlt: '',
      detail:'',
      imageProfile: '',
    },
    {
      id: 4,
      name: 'Louis Vuitton',
      imageSrc: 'https://images.pexels.com/photos/7691003/pexels-photo-7691003.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      imageAlt: '',
      detail:'',
      imageProfile: '',
    },
    {
      id: 5,
      name: 'Executive',
      imageSrc: 'https://images.pexels.com/photos/6732346/pexels-photo-6732346.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      imageAlt: '',
      detail: '',
      imageProfile: '',
    },
    {
      id: 6,
      name: 'Puma',
      imageSrc: 'https://images.pexels.com/photos/6389848/pexels-photo-6389848.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      imageAlt: '',
      detail:'',
      imageProfile: '',
    },
    {
      id: 7,
      name: 'Erigo',
      imageSrc: 'https://images.pexels.com/photos/7228467/pexels-photo-7228467.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      imageAlt: '',
      detail:'',
      imageProfile: '',
    },
    {
      id: 8,
      name: 'Gucci',
      imageSrc: 'https://images.pexels.com/photos/3854884/pexels-photo-3854884.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      imageAlt: '',
      detail:'',
      imageProfile: '',
    },
    {
      id: 9,
      name: 'Kivitz',
      imageSrc: 'https://images.pexels.com/photos/4205567/pexels-photo-4205567.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      imageAlt: '',
      detail:'',
      imageProfile: '',
    },
    {
      id: 10,
      name: 'Hermes',
      imageSrc: 'https://images.pexels.com/photos/11190774/pexels-photo-11190774.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      imageAlt: '',
      detail:'',
      imageProfile: '',
    },
    {
      id: 11,
      name: 'Coach',
      imageSrc: 'https://images.pexels.com/photos/7765972/pexels-photo-7765972.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      imageAlt: '',
      detail:'',
      imageProfile: '',
      imageAltProfile:'',
    },
    {
      id: 12,
      name: 'Uniqlo',
      imageSrc: 'https://images.pexels.com/photos/6774990/pexels-photo-6774990.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      imageAlt: '',
      detail:'asdasdaaa',
      imageProfile: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMoAAAD5CAMAAABRVVqZAAAAA1BMVEWAgICQdD0xAAAAR0lEQVR4nO3BAQEAAACCIP+vbkhAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcGxXMAAfH9TEUAAAAASUVORK5CYII=',
      imageAltProfile: '',
    },
    {
        id: 13,
        name: 'Zalando',
        imageSrc: 'https://images.pexels.com/photos/157675/fashion-men-s-individuality-black-and-white-157675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 14,
        name: 'T&C',
        imageSrc: 'https://images.pexels.com/photos/1661417/pexels-photo-1661417.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 15,
        name: 'H&M',
        imageSrc: 'https://images.pexels.com/photos/965324/pexels-photo-965324.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 16,
        name: 'Cartier',
        imageSrc: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 17,
        name: 'Lululemon',
        imageSrc: 'https://images.pexels.com/photos/2072057/pexels-photo-2072057.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 18,
        name: 'Moncler',
        imageSrc: 'https://images.pexels.com/photos/1852382/pexels-photo-1852382.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 19,
        name: 'Chanel',
        imageSrc: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 20,
        name: 'Prada',
        imageSrc: 'https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 21,
        name: 'Tom Ford',
        imageSrc: 'https://images.pexels.com/photos/1381556/pexels-photo-1381556.jpeg',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 22,
        name: 'Next',
        imageSrc: 'https://images.pexels.com/photos/1163194/pexels-photo-1163194.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 23,
        name: 'Steve Madden',
        imageSrc: 'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
    {
        id: 24,
        name: 'Brunello Cucinelli',
        imageSrc: 'https://images.pexels.com/photos/157675/fashion-men-s-individuality-black-and-white-157675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        imageAlt: '',
        detail:'',
        imageProfile: '',
    },
  ]
  
  export default exploredata;